# Generated by Django 5.2.1 on 2025-08-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_created_at_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='platforms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
