# Generated by Django 5.2.1 on 2025-08-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
