# Generated by Django 5.2.1 on 2025-08-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_post_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_url',
            new_name='facebook_url',
        ),
        migrations.AddField(
            model_name='post',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
